name: Build

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Compile
        run: mvn -T 1C --batch-mode -Dstyle.color=always --fail-at-end -DskipTests package
      - name: Test
        run: mvn --batch-mode -Dstyle.color=always --fail-at-end verify
      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
